David Diaz, Arbol de desicion.

## Importación de librerias

Se cargan las librerias necesarias para la implementacion

In [1]:
# Librerías para manejo de datos
import pandas as pd
pd.set_option('display.max_columns', 25) # Número máximo de columnas a mostrar
pd.set_option('display.max_rows', 50) # Numero máximo de filas a mostar
import numpy as np
np.random.seed(3301)
import pandas as pd
# Para preparar los datos
from sklearn.preprocessing import LabelEncoder
# Para crear el arbol de decisión 
from sklearn.tree import DecisionTreeClassifier 
# Para realizar la separación del conjunto de aprendizaje en entrenamiento y test.
from sklearn.model_selection import train_test_split
# Para evaluar el modelo
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score, f1_score, accuracy_score
from sklearn.metrics import plot_confusion_matrix
# Para búsqueda de hiperparámetros
from sklearn.model_selection import GridSearchCV
# Para la validación cruzada
from sklearn.model_selection import KFold 
#Librerías para la visualización
import matplotlib.pyplot as plt
# Seaborn
import seaborn as sns 
from sklearn import tree

## Carga de datos

A través de la librería pandas podemos realizar la carga de datos desde diferentes fuentes de información, en este caso se realizará la carga de un archivo plano csv (archivo separado por comas).

In [4]:
# Se cargan los datos. 
df_salud=pd.read_csv('202220_Laboratorio_1_data_heart_disease_data.csv', sep=',', encoding = 'utf-8')

In [5]:
df_salud.shape

(67500, 19)

In [6]:
df_salud.head()

,Index,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,HeartDisease
0,0,26.5,No,No,No,0.0,0.0,No,Male,64-60,White,No,Yes,Very good,8.0,No,No,No,No
1,1,28.75,ýNoÚ,No,No,0.0,2.0,No,Male,59-55,White,No,Yes,Very good,7.0,No,No,No,No
2,2,19.9,Yes,No,No,0.0,1.0,No,Male,39-35,White,No,Yes,Good,7.0,No,No,No,No
3,3,28.06,No,No,No,1.0,1.0,No,Female,69-65,White,Yes,Yes,Good,8.0,No,No,No,£NoÇ
4,4,29.29,Yes,No,No,0.0,1.0,No,Female,74-70,White,No,Yes,Very good,7.0,Yes,No,No,No

In [7]:
df_salud.dtypes

Index                 int64
BMI                  object
Smoking              object
AlcoholDrinking      object
Stroke               object
PhysicalHealth       object
MentalHealth         object
DiffWalking          object
Sex                  object
AgeCategory          object
Race                 object
Diabetic             object
PhysicalActivity     object
GenHealth            object
SleepTime           float64
Asthma               object
KidneyDisease        object
SkinCancer           object
HeartDisease         object
dtype: object

In [8]:
df_salud.describe()

              Index     SleepTime
count  67500.000000  67500.000000
mean   33749.500000     10.223081
std    19485.715922     26.028973
min        0.000000    -20.000000
25%    16874.750000      6.000000
50%    33749.500000      7.000000
75%    50624.250000      8.000000
max    67499.000000    406.000000

## Perfilamiento de los datos

El archivo comprende 19 columnas de infomación de las cuales 1  son int64, una float64 y las otras estan definidas como objetos, al ver la cabeza del archivo, se puede persivir que es necesario hacer un filtrado, ya que 5 de las 11 columnas son aparentemente numericas y 9 booleanas.

En cuanto al perfilamiento de datos, se van a definir variables adicionales para agregar la clasificacion en las columnas que tienen campos con rango de normalidad. (Glucosa, Preison)

Ademas, se observa que la columna Ciudad es irrelevante para el estudio de los datos, por lo tanto se puede eliminar. Paralelamente para que el algoritmo funcione correctamente, se debe eliminar la columna outcome si queremos obtener una buena funcion.

Por otro lado, el valor de la columna BMI esta mal ya que no tiene la coma decimal, por lo tanto se debe corregir toda la columna, Aunque si pueden haber valores altos de BMI uno superior a 100 es inhumano.